### ISSUE TITLE
[Bug]:  Downloading assets fails and responds 410 status

### ISSUE THREAD

**Issue by tenesh-inpsyde** [inpsyde/composer-asset-compiler#24]
### Description of the bug

The recent merge commit https://github.com/inpsyde/composer-asset-compiler/commit/793bc8e3972ed975029327029aa934bc34577f60 leads to  [410] status when downloading the assets. The build ends up stuck without moving further.

![image](https://github.com/inpsyde/composer-asset-compiler/assets/99238839/0251ae95-2d3d-4ae2-8386-59e1a9d1ac01)

Looks like the merge commit stated above left out  `!`  right here https://github.com/inpsyde/composer-asset-compiler/blob/509c82ff5c11a1587228e92f2771c7d6984b4b61/src/PreCompilation/GithubActionArtifactAdapter.php#L180

Please compare with this commit https://github.com/inpsyde/composer-asset-compiler/commit/c6af6420cae7d44feeeaf48c04347399ab3e6f35 on the difference.

### Reproduction instructions

1. Setup a repository with  a dependency on version constraint. 
2. Execute the command  ` composer compile-assets -vvv` to view the log on [401] during downloading assets for the dependency.  

### Expected behavior

Assets should be installed with default configuration or use preprocessed assets when a valid API response is not obtained.

### Environment info

- Package version : master

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gmazzap** [comment]
Thank you @tenesh-inpsyde 
Can you please test now? If it works, I'll release a new version in th 2.x series

**Comment by tenesh-inpsyde** [comment]
Hi @gmazzap ,

I have tested and it is working now. Thank you for the prompt fix! 👍🏽

**Comment by gmazzap** [comment]
Thanks @tenesh-inpsyde 

https://github.com/inpsyde/composer-asset-compiler/releases/tag/2.5.3
